# Generated by Django 3.2.9 on 2022-04-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_worker_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='deals',
            field=models.ManyToManyField(to='api.Deal'),
        ),
    ]
